---
- debug:
    var: username

- name: Hash passwords
  shell: >
    bash {{ os_home }}/plugins/opensearch-security/tools/hash.sh -p {{ username.value.password }} | tail -n 1
  environment:
    JAVA_HOME: "{{ os_home }}/jdk"
  register: pwdhashtool

- debug:
    var: pwdhashtool

- set_fact:
    _username: "{{ username.value | combine( { 'hash': pwdhashtool.stdout } ) }}"

- debug:
    var: _username
